spring.application.name=graphql-demo

# Cấu hình SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GraphQL_Store;encrypt=true;trustServerCertificate=true;
spring.datasource.username=vuthibac1106
spring.datasource.password=200539Huy
# (Thay 12345678 bằng mật khẩu SQL của bạn)

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Bật công cụ test GraphQL (GraphiQL)
spring.graphql.graphiql.enabled=true